// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"sync"

	discorda "github.com/disgoorg/disgo/discord"
	"github.com/disgoorg/disgo/rest"
	snowflake "github.com/disgoorg/snowflake/v2"
	"github.com/geofffranks/rookies-bot/discord"
)

type FakeBotRestClient struct {
	CreateGuildScheduledEventStub        func(snowflake.ID, discorda.GuildScheduledEventCreate, ...rest.RequestOpt) (*discorda.GuildScheduledEvent, error)
	createGuildScheduledEventMutex       sync.RWMutex
	createGuildScheduledEventArgsForCall []struct {
		arg1 snowflake.ID
		arg2 discorda.GuildScheduledEventCreate
		arg3 []rest.RequestOpt
	}
	createGuildScheduledEventReturns struct {
		result1 *discorda.GuildScheduledEvent
		result2 error
	}
	createGuildScheduledEventReturnsOnCall map[int]struct {
		result1 *discorda.GuildScheduledEvent
		result2 error
	}
	CreateMessageStub        func(snowflake.ID, discorda.MessageCreate, ...rest.RequestOpt) (*discorda.Message, error)
	createMessageMutex       sync.RWMutex
	createMessageArgsForCall []struct {
		arg1 snowflake.ID
		arg2 discorda.MessageCreate
		arg3 []rest.RequestOpt
	}
	createMessageReturns struct {
		result1 *discorda.Message
		result2 error
	}
	createMessageReturnsOnCall map[int]struct {
		result1 *discorda.Message
		result2 error
	}
	GetChannelStub        func(snowflake.ID, ...rest.RequestOpt) (discorda.Channel, error)
	getChannelMutex       sync.RWMutex
	getChannelArgsForCall []struct {
		arg1 snowflake.ID
		arg2 []rest.RequestOpt
	}
	getChannelReturns struct {
		result1 discorda.Channel
		result2 error
	}
	getChannelReturnsOnCall map[int]struct {
		result1 discorda.Channel
		result2 error
	}
	GetMembersStub        func(snowflake.ID, int, snowflake.ID, ...rest.RequestOpt) ([]discorda.Member, error)
	getMembersMutex       sync.RWMutex
	getMembersArgsForCall []struct {
		arg1 snowflake.ID
		arg2 int
		arg3 snowflake.ID
		arg4 []rest.RequestOpt
	}
	getMembersReturns struct {
		result1 []discorda.Member
		result2 error
	}
	getMembersReturnsOnCall map[int]struct {
		result1 []discorda.Member
		result2 error
	}
	GetPinnedMessagesStub        func(snowflake.ID, ...rest.RequestOpt) ([]discorda.Message, error)
	getPinnedMessagesMutex       sync.RWMutex
	getPinnedMessagesArgsForCall []struct {
		arg1 snowflake.ID
		arg2 []rest.RequestOpt
	}
	getPinnedMessagesReturns struct {
		result1 []discorda.Message
		result2 error
	}
	getPinnedMessagesReturnsOnCall map[int]struct {
		result1 []discorda.Message
		result2 error
	}
	GetRolesStub        func(snowflake.ID, ...rest.RequestOpt) ([]discorda.Role, error)
	getRolesMutex       sync.RWMutex
	getRolesArgsForCall []struct {
		arg1 snowflake.ID
		arg2 []rest.RequestOpt
	}
	getRolesReturns struct {
		result1 []discorda.Role
		result2 error
	}
	getRolesReturnsOnCall map[int]struct {
		result1 []discorda.Role
		result2 error
	}
	PinMessageStub        func(snowflake.ID, snowflake.ID, ...rest.RequestOpt) error
	pinMessageMutex       sync.RWMutex
	pinMessageArgsForCall []struct {
		arg1 snowflake.ID
		arg2 snowflake.ID
		arg3 []rest.RequestOpt
	}
	pinMessageReturns struct {
		result1 error
	}
	pinMessageReturnsOnCall map[int]struct {
		result1 error
	}
	UnpinMessageStub        func(snowflake.ID, snowflake.ID, ...rest.RequestOpt) error
	unpinMessageMutex       sync.RWMutex
	unpinMessageArgsForCall []struct {
		arg1 snowflake.ID
		arg2 snowflake.ID
		arg3 []rest.RequestOpt
	}
	unpinMessageReturns struct {
		result1 error
	}
	unpinMessageReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeBotRestClient) CreateGuildScheduledEvent(arg1 snowflake.ID, arg2 discorda.GuildScheduledEventCreate, arg3 ...rest.RequestOpt) (*discorda.GuildScheduledEvent, error) {
	fake.createGuildScheduledEventMutex.Lock()
	ret, specificReturn := fake.createGuildScheduledEventReturnsOnCall[len(fake.createGuildScheduledEventArgsForCall)]
	fake.createGuildScheduledEventArgsForCall = append(fake.createGuildScheduledEventArgsForCall, struct {
		arg1 snowflake.ID
		arg2 discorda.GuildScheduledEventCreate
		arg3 []rest.RequestOpt
	}{arg1, arg2, arg3})
	stub := fake.CreateGuildScheduledEventStub
	fakeReturns := fake.createGuildScheduledEventReturns
	fake.recordInvocation("CreateGuildScheduledEvent", []interface{}{arg1, arg2, arg3})
	fake.createGuildScheduledEventMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3...)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeBotRestClient) CreateGuildScheduledEventCallCount() int {
	fake.createGuildScheduledEventMutex.RLock()
	defer fake.createGuildScheduledEventMutex.RUnlock()
	return len(fake.createGuildScheduledEventArgsForCall)
}

func (fake *FakeBotRestClient) CreateGuildScheduledEventCalls(stub func(snowflake.ID, discorda.GuildScheduledEventCreate, ...rest.RequestOpt) (*discorda.GuildScheduledEvent, error)) {
	fake.createGuildScheduledEventMutex.Lock()
	defer fake.createGuildScheduledEventMutex.Unlock()
	fake.CreateGuildScheduledEventStub = stub
}

func (fake *FakeBotRestClient) CreateGuildScheduledEventArgsForCall(i int) (snowflake.ID, discorda.GuildScheduledEventCreate, []rest.RequestOpt) {
	fake.createGuildScheduledEventMutex.RLock()
	defer fake.createGuildScheduledEventMutex.RUnlock()
	argsForCall := fake.createGuildScheduledEventArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeBotRestClient) CreateGuildScheduledEventReturns(result1 *discorda.GuildScheduledEvent, result2 error) {
	fake.createGuildScheduledEventMutex.Lock()
	defer fake.createGuildScheduledEventMutex.Unlock()
	fake.CreateGuildScheduledEventStub = nil
	fake.createGuildScheduledEventReturns = struct {
		result1 *discorda.GuildScheduledEvent
		result2 error
	}{result1, result2}
}

func (fake *FakeBotRestClient) CreateGuildScheduledEventReturnsOnCall(i int, result1 *discorda.GuildScheduledEvent, result2 error) {
	fake.createGuildScheduledEventMutex.Lock()
	defer fake.createGuildScheduledEventMutex.Unlock()
	fake.CreateGuildScheduledEventStub = nil
	if fake.createGuildScheduledEventReturnsOnCall == nil {
		fake.createGuildScheduledEventReturnsOnCall = make(map[int]struct {
			result1 *discorda.GuildScheduledEvent
			result2 error
		})
	}
	fake.createGuildScheduledEventReturnsOnCall[i] = struct {
		result1 *discorda.GuildScheduledEvent
		result2 error
	}{result1, result2}
}

func (fake *FakeBotRestClient) CreateMessage(arg1 snowflake.ID, arg2 discorda.MessageCreate, arg3 ...rest.RequestOpt) (*discorda.Message, error) {
	fake.createMessageMutex.Lock()
	ret, specificReturn := fake.createMessageReturnsOnCall[len(fake.createMessageArgsForCall)]
	fake.createMessageArgsForCall = append(fake.createMessageArgsForCall, struct {
		arg1 snowflake.ID
		arg2 discorda.MessageCreate
		arg3 []rest.RequestOpt
	}{arg1, arg2, arg3})
	stub := fake.CreateMessageStub
	fakeReturns := fake.createMessageReturns
	fake.recordInvocation("CreateMessage", []interface{}{arg1, arg2, arg3})
	fake.createMessageMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3...)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeBotRestClient) CreateMessageCallCount() int {
	fake.createMessageMutex.RLock()
	defer fake.createMessageMutex.RUnlock()
	return len(fake.createMessageArgsForCall)
}

func (fake *FakeBotRestClient) CreateMessageCalls(stub func(snowflake.ID, discorda.MessageCreate, ...rest.RequestOpt) (*discorda.Message, error)) {
	fake.createMessageMutex.Lock()
	defer fake.createMessageMutex.Unlock()
	fake.CreateMessageStub = stub
}

func (fake *FakeBotRestClient) CreateMessageArgsForCall(i int) (snowflake.ID, discorda.MessageCreate, []rest.RequestOpt) {
	fake.createMessageMutex.RLock()
	defer fake.createMessageMutex.RUnlock()
	argsForCall := fake.createMessageArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeBotRestClient) CreateMessageReturns(result1 *discorda.Message, result2 error) {
	fake.createMessageMutex.Lock()
	defer fake.createMessageMutex.Unlock()
	fake.CreateMessageStub = nil
	fake.createMessageReturns = struct {
		result1 *discorda.Message
		result2 error
	}{result1, result2}
}

func (fake *FakeBotRestClient) CreateMessageReturnsOnCall(i int, result1 *discorda.Message, result2 error) {
	fake.createMessageMutex.Lock()
	defer fake.createMessageMutex.Unlock()
	fake.CreateMessageStub = nil
	if fake.createMessageReturnsOnCall == nil {
		fake.createMessageReturnsOnCall = make(map[int]struct {
			result1 *discorda.Message
			result2 error
		})
	}
	fake.createMessageReturnsOnCall[i] = struct {
		result1 *discorda.Message
		result2 error
	}{result1, result2}
}

func (fake *FakeBotRestClient) GetChannel(arg1 snowflake.ID, arg2 ...rest.RequestOpt) (discorda.Channel, error) {
	fake.getChannelMutex.Lock()
	ret, specificReturn := fake.getChannelReturnsOnCall[len(fake.getChannelArgsForCall)]
	fake.getChannelArgsForCall = append(fake.getChannelArgsForCall, struct {
		arg1 snowflake.ID
		arg2 []rest.RequestOpt
	}{arg1, arg2})
	stub := fake.GetChannelStub
	fakeReturns := fake.getChannelReturns
	fake.recordInvocation("GetChannel", []interface{}{arg1, arg2})
	fake.getChannelMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2...)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeBotRestClient) GetChannelCallCount() int {
	fake.getChannelMutex.RLock()
	defer fake.getChannelMutex.RUnlock()
	return len(fake.getChannelArgsForCall)
}

func (fake *FakeBotRestClient) GetChannelCalls(stub func(snowflake.ID, ...rest.RequestOpt) (discorda.Channel, error)) {
	fake.getChannelMutex.Lock()
	defer fake.getChannelMutex.Unlock()
	fake.GetChannelStub = stub
}

func (fake *FakeBotRestClient) GetChannelArgsForCall(i int) (snowflake.ID, []rest.RequestOpt) {
	fake.getChannelMutex.RLock()
	defer fake.getChannelMutex.RUnlock()
	argsForCall := fake.getChannelArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeBotRestClient) GetChannelReturns(result1 discorda.Channel, result2 error) {
	fake.getChannelMutex.Lock()
	defer fake.getChannelMutex.Unlock()
	fake.GetChannelStub = nil
	fake.getChannelReturns = struct {
		result1 discorda.Channel
		result2 error
	}{result1, result2}
}

func (fake *FakeBotRestClient) GetChannelReturnsOnCall(i int, result1 discorda.Channel, result2 error) {
	fake.getChannelMutex.Lock()
	defer fake.getChannelMutex.Unlock()
	fake.GetChannelStub = nil
	if fake.getChannelReturnsOnCall == nil {
		fake.getChannelReturnsOnCall = make(map[int]struct {
			result1 discorda.Channel
			result2 error
		})
	}
	fake.getChannelReturnsOnCall[i] = struct {
		result1 discorda.Channel
		result2 error
	}{result1, result2}
}

func (fake *FakeBotRestClient) GetMembers(arg1 snowflake.ID, arg2 int, arg3 snowflake.ID, arg4 ...rest.RequestOpt) ([]discorda.Member, error) {
	fake.getMembersMutex.Lock()
	ret, specificReturn := fake.getMembersReturnsOnCall[len(fake.getMembersArgsForCall)]
	fake.getMembersArgsForCall = append(fake.getMembersArgsForCall, struct {
		arg1 snowflake.ID
		arg2 int
		arg3 snowflake.ID
		arg4 []rest.RequestOpt
	}{arg1, arg2, arg3, arg4})
	stub := fake.GetMembersStub
	fakeReturns := fake.getMembersReturns
	fake.recordInvocation("GetMembers", []interface{}{arg1, arg2, arg3, arg4})
	fake.getMembersMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4...)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeBotRestClient) GetMembersCallCount() int {
	fake.getMembersMutex.RLock()
	defer fake.getMembersMutex.RUnlock()
	return len(fake.getMembersArgsForCall)
}

func (fake *FakeBotRestClient) GetMembersCalls(stub func(snowflake.ID, int, snowflake.ID, ...rest.RequestOpt) ([]discorda.Member, error)) {
	fake.getMembersMutex.Lock()
	defer fake.getMembersMutex.Unlock()
	fake.GetMembersStub = stub
}

func (fake *FakeBotRestClient) GetMembersArgsForCall(i int) (snowflake.ID, int, snowflake.ID, []rest.RequestOpt) {
	fake.getMembersMutex.RLock()
	defer fake.getMembersMutex.RUnlock()
	argsForCall := fake.getMembersArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakeBotRestClient) GetMembersReturns(result1 []discorda.Member, result2 error) {
	fake.getMembersMutex.Lock()
	defer fake.getMembersMutex.Unlock()
	fake.GetMembersStub = nil
	fake.getMembersReturns = struct {
		result1 []discorda.Member
		result2 error
	}{result1, result2}
}

func (fake *FakeBotRestClient) GetMembersReturnsOnCall(i int, result1 []discorda.Member, result2 error) {
	fake.getMembersMutex.Lock()
	defer fake.getMembersMutex.Unlock()
	fake.GetMembersStub = nil
	if fake.getMembersReturnsOnCall == nil {
		fake.getMembersReturnsOnCall = make(map[int]struct {
			result1 []discorda.Member
			result2 error
		})
	}
	fake.getMembersReturnsOnCall[i] = struct {
		result1 []discorda.Member
		result2 error
	}{result1, result2}
}

func (fake *FakeBotRestClient) GetPinnedMessages(arg1 snowflake.ID, arg2 ...rest.RequestOpt) ([]discorda.Message, error) {
	fake.getPinnedMessagesMutex.Lock()
	ret, specificReturn := fake.getPinnedMessagesReturnsOnCall[len(fake.getPinnedMessagesArgsForCall)]
	fake.getPinnedMessagesArgsForCall = append(fake.getPinnedMessagesArgsForCall, struct {
		arg1 snowflake.ID
		arg2 []rest.RequestOpt
	}{arg1, arg2})
	stub := fake.GetPinnedMessagesStub
	fakeReturns := fake.getPinnedMessagesReturns
	fake.recordInvocation("GetPinnedMessages", []interface{}{arg1, arg2})
	fake.getPinnedMessagesMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2...)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeBotRestClient) GetPinnedMessagesCallCount() int {
	fake.getPinnedMessagesMutex.RLock()
	defer fake.getPinnedMessagesMutex.RUnlock()
	return len(fake.getPinnedMessagesArgsForCall)
}

func (fake *FakeBotRestClient) GetPinnedMessagesCalls(stub func(snowflake.ID, ...rest.RequestOpt) ([]discorda.Message, error)) {
	fake.getPinnedMessagesMutex.Lock()
	defer fake.getPinnedMessagesMutex.Unlock()
	fake.GetPinnedMessagesStub = stub
}

func (fake *FakeBotRestClient) GetPinnedMessagesArgsForCall(i int) (snowflake.ID, []rest.RequestOpt) {
	fake.getPinnedMessagesMutex.RLock()
	defer fake.getPinnedMessagesMutex.RUnlock()
	argsForCall := fake.getPinnedMessagesArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeBotRestClient) GetPinnedMessagesReturns(result1 []discorda.Message, result2 error) {
	fake.getPinnedMessagesMutex.Lock()
	defer fake.getPinnedMessagesMutex.Unlock()
	fake.GetPinnedMessagesStub = nil
	fake.getPinnedMessagesReturns = struct {
		result1 []discorda.Message
		result2 error
	}{result1, result2}
}

func (fake *FakeBotRestClient) GetPinnedMessagesReturnsOnCall(i int, result1 []discorda.Message, result2 error) {
	fake.getPinnedMessagesMutex.Lock()
	defer fake.getPinnedMessagesMutex.Unlock()
	fake.GetPinnedMessagesStub = nil
	if fake.getPinnedMessagesReturnsOnCall == nil {
		fake.getPinnedMessagesReturnsOnCall = make(map[int]struct {
			result1 []discorda.Message
			result2 error
		})
	}
	fake.getPinnedMessagesReturnsOnCall[i] = struct {
		result1 []discorda.Message
		result2 error
	}{result1, result2}
}

func (fake *FakeBotRestClient) GetRoles(arg1 snowflake.ID, arg2 ...rest.RequestOpt) ([]discorda.Role, error) {
	fake.getRolesMutex.Lock()
	ret, specificReturn := fake.getRolesReturnsOnCall[len(fake.getRolesArgsForCall)]
	fake.getRolesArgsForCall = append(fake.getRolesArgsForCall, struct {
		arg1 snowflake.ID
		arg2 []rest.RequestOpt
	}{arg1, arg2})
	stub := fake.GetRolesStub
	fakeReturns := fake.getRolesReturns
	fake.recordInvocation("GetRoles", []interface{}{arg1, arg2})
	fake.getRolesMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2...)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeBotRestClient) GetRolesCallCount() int {
	fake.getRolesMutex.RLock()
	defer fake.getRolesMutex.RUnlock()
	return len(fake.getRolesArgsForCall)
}

func (fake *FakeBotRestClient) GetRolesCalls(stub func(snowflake.ID, ...rest.RequestOpt) ([]discorda.Role, error)) {
	fake.getRolesMutex.Lock()
	defer fake.getRolesMutex.Unlock()
	fake.GetRolesStub = stub
}

func (fake *FakeBotRestClient) GetRolesArgsForCall(i int) (snowflake.ID, []rest.RequestOpt) {
	fake.getRolesMutex.RLock()
	defer fake.getRolesMutex.RUnlock()
	argsForCall := fake.getRolesArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeBotRestClient) GetRolesReturns(result1 []discorda.Role, result2 error) {
	fake.getRolesMutex.Lock()
	defer fake.getRolesMutex.Unlock()
	fake.GetRolesStub = nil
	fake.getRolesReturns = struct {
		result1 []discorda.Role
		result2 error
	}{result1, result2}
}

func (fake *FakeBotRestClient) GetRolesReturnsOnCall(i int, result1 []discorda.Role, result2 error) {
	fake.getRolesMutex.Lock()
	defer fake.getRolesMutex.Unlock()
	fake.GetRolesStub = nil
	if fake.getRolesReturnsOnCall == nil {
		fake.getRolesReturnsOnCall = make(map[int]struct {
			result1 []discorda.Role
			result2 error
		})
	}
	fake.getRolesReturnsOnCall[i] = struct {
		result1 []discorda.Role
		result2 error
	}{result1, result2}
}

func (fake *FakeBotRestClient) PinMessage(arg1 snowflake.ID, arg2 snowflake.ID, arg3 ...rest.RequestOpt) error {
	fake.pinMessageMutex.Lock()
	ret, specificReturn := fake.pinMessageReturnsOnCall[len(fake.pinMessageArgsForCall)]
	fake.pinMessageArgsForCall = append(fake.pinMessageArgsForCall, struct {
		arg1 snowflake.ID
		arg2 snowflake.ID
		arg3 []rest.RequestOpt
	}{arg1, arg2, arg3})
	stub := fake.PinMessageStub
	fakeReturns := fake.pinMessageReturns
	fake.recordInvocation("PinMessage", []interface{}{arg1, arg2, arg3})
	fake.pinMessageMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3...)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeBotRestClient) PinMessageCallCount() int {
	fake.pinMessageMutex.RLock()
	defer fake.pinMessageMutex.RUnlock()
	return len(fake.pinMessageArgsForCall)
}

func (fake *FakeBotRestClient) PinMessageCalls(stub func(snowflake.ID, snowflake.ID, ...rest.RequestOpt) error) {
	fake.pinMessageMutex.Lock()
	defer fake.pinMessageMutex.Unlock()
	fake.PinMessageStub = stub
}

func (fake *FakeBotRestClient) PinMessageArgsForCall(i int) (snowflake.ID, snowflake.ID, []rest.RequestOpt) {
	fake.pinMessageMutex.RLock()
	defer fake.pinMessageMutex.RUnlock()
	argsForCall := fake.pinMessageArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeBotRestClient) PinMessageReturns(result1 error) {
	fake.pinMessageMutex.Lock()
	defer fake.pinMessageMutex.Unlock()
	fake.PinMessageStub = nil
	fake.pinMessageReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeBotRestClient) PinMessageReturnsOnCall(i int, result1 error) {
	fake.pinMessageMutex.Lock()
	defer fake.pinMessageMutex.Unlock()
	fake.PinMessageStub = nil
	if fake.pinMessageReturnsOnCall == nil {
		fake.pinMessageReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.pinMessageReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeBotRestClient) UnpinMessage(arg1 snowflake.ID, arg2 snowflake.ID, arg3 ...rest.RequestOpt) error {
	fake.unpinMessageMutex.Lock()
	ret, specificReturn := fake.unpinMessageReturnsOnCall[len(fake.unpinMessageArgsForCall)]
	fake.unpinMessageArgsForCall = append(fake.unpinMessageArgsForCall, struct {
		arg1 snowflake.ID
		arg2 snowflake.ID
		arg3 []rest.RequestOpt
	}{arg1, arg2, arg3})
	stub := fake.UnpinMessageStub
	fakeReturns := fake.unpinMessageReturns
	fake.recordInvocation("UnpinMessage", []interface{}{arg1, arg2, arg3})
	fake.unpinMessageMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3...)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeBotRestClient) UnpinMessageCallCount() int {
	fake.unpinMessageMutex.RLock()
	defer fake.unpinMessageMutex.RUnlock()
	return len(fake.unpinMessageArgsForCall)
}

func (fake *FakeBotRestClient) UnpinMessageCalls(stub func(snowflake.ID, snowflake.ID, ...rest.RequestOpt) error) {
	fake.unpinMessageMutex.Lock()
	defer fake.unpinMessageMutex.Unlock()
	fake.UnpinMessageStub = stub
}

func (fake *FakeBotRestClient) UnpinMessageArgsForCall(i int) (snowflake.ID, snowflake.ID, []rest.RequestOpt) {
	fake.unpinMessageMutex.RLock()
	defer fake.unpinMessageMutex.RUnlock()
	argsForCall := fake.unpinMessageArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeBotRestClient) UnpinMessageReturns(result1 error) {
	fake.unpinMessageMutex.Lock()
	defer fake.unpinMessageMutex.Unlock()
	fake.UnpinMessageStub = nil
	fake.unpinMessageReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeBotRestClient) UnpinMessageReturnsOnCall(i int, result1 error) {
	fake.unpinMessageMutex.Lock()
	defer fake.unpinMessageMutex.Unlock()
	fake.UnpinMessageStub = nil
	if fake.unpinMessageReturnsOnCall == nil {
		fake.unpinMessageReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.unpinMessageReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeBotRestClient) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeBotRestClient) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ discord.BotRestClient = new(FakeBotRestClient)
