// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"context"
	"sync"

	"github.com/geofffranks/rookies-bot/discord"
)

type FakeBotDiscordClient struct {
	CloseStub        func(context.Context)
	closeMutex       sync.RWMutex
	closeArgsForCall []struct {
		arg1 context.Context
	}
	OpenGatewayStub        func(context.Context) error
	openGatewayMutex       sync.RWMutex
	openGatewayArgsForCall []struct {
		arg1 context.Context
	}
	openGatewayReturns struct {
		result1 error
	}
	openGatewayReturnsOnCall map[int]struct {
		result1 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeBotDiscordClient) Close(arg1 context.Context) {
	fake.closeMutex.Lock()
	fake.closeArgsForCall = append(fake.closeArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.CloseStub
	fake.recordInvocation("Close", []interface{}{arg1})
	fake.closeMutex.Unlock()
	if stub != nil {
		fake.CloseStub(arg1)
	}
}

func (fake *FakeBotDiscordClient) CloseCallCount() int {
	fake.closeMutex.RLock()
	defer fake.closeMutex.RUnlock()
	return len(fake.closeArgsForCall)
}

func (fake *FakeBotDiscordClient) CloseCalls(stub func(context.Context)) {
	fake.closeMutex.Lock()
	defer fake.closeMutex.Unlock()
	fake.CloseStub = stub
}

func (fake *FakeBotDiscordClient) CloseArgsForCall(i int) context.Context {
	fake.closeMutex.RLock()
	defer fake.closeMutex.RUnlock()
	argsForCall := fake.closeArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeBotDiscordClient) OpenGateway(arg1 context.Context) error {
	fake.openGatewayMutex.Lock()
	ret, specificReturn := fake.openGatewayReturnsOnCall[len(fake.openGatewayArgsForCall)]
	fake.openGatewayArgsForCall = append(fake.openGatewayArgsForCall, struct {
		arg1 context.Context
	}{arg1})
	stub := fake.OpenGatewayStub
	fakeReturns := fake.openGatewayReturns
	fake.recordInvocation("OpenGateway", []interface{}{arg1})
	fake.openGatewayMutex.Unlock()
	if stub != nil {
		return stub(arg1)
	}
	if specificReturn {
		return ret.result1
	}
	return fakeReturns.result1
}

func (fake *FakeBotDiscordClient) OpenGatewayCallCount() int {
	fake.openGatewayMutex.RLock()
	defer fake.openGatewayMutex.RUnlock()
	return len(fake.openGatewayArgsForCall)
}

func (fake *FakeBotDiscordClient) OpenGatewayCalls(stub func(context.Context) error) {
	fake.openGatewayMutex.Lock()
	defer fake.openGatewayMutex.Unlock()
	fake.OpenGatewayStub = stub
}

func (fake *FakeBotDiscordClient) OpenGatewayArgsForCall(i int) context.Context {
	fake.openGatewayMutex.RLock()
	defer fake.openGatewayMutex.RUnlock()
	argsForCall := fake.openGatewayArgsForCall[i]
	return argsForCall.arg1
}

func (fake *FakeBotDiscordClient) OpenGatewayReturns(result1 error) {
	fake.openGatewayMutex.Lock()
	defer fake.openGatewayMutex.Unlock()
	fake.OpenGatewayStub = nil
	fake.openGatewayReturns = struct {
		result1 error
	}{result1}
}

func (fake *FakeBotDiscordClient) OpenGatewayReturnsOnCall(i int, result1 error) {
	fake.openGatewayMutex.Lock()
	defer fake.openGatewayMutex.Unlock()
	fake.OpenGatewayStub = nil
	if fake.openGatewayReturnsOnCall == nil {
		fake.openGatewayReturnsOnCall = make(map[int]struct {
			result1 error
		})
	}
	fake.openGatewayReturnsOnCall[i] = struct {
		result1 error
	}{result1}
}

func (fake *FakeBotDiscordClient) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeBotDiscordClient) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ discord.BotDiscordClient = new(FakeBotDiscordClient)
