// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"context"
	"sync"

	"github.com/geofffranks/rookies-bot/gcloud"
	docs "google.golang.org/api/docs/v1"
)

type FakeDocsServicer struct {
	BatchUpdateDocumentStub        func(context.Context, string, *docs.BatchUpdateDocumentRequest) (*docs.BatchUpdateDocumentResponse, error)
	batchUpdateDocumentMutex       sync.RWMutex
	batchUpdateDocumentArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 *docs.BatchUpdateDocumentRequest
	}
	batchUpdateDocumentReturns struct {
		result1 *docs.BatchUpdateDocumentResponse
		result2 error
	}
	batchUpdateDocumentReturnsOnCall map[int]struct {
		result1 *docs.BatchUpdateDocumentResponse
		result2 error
	}
	GetDocumentStub        func(context.Context, string) (*docs.Document, error)
	getDocumentMutex       sync.RWMutex
	getDocumentArgsForCall []struct {
		arg1 context.Context
		arg2 string
	}
	getDocumentReturns struct {
		result1 *docs.Document
		result2 error
	}
	getDocumentReturnsOnCall map[int]struct {
		result1 *docs.Document
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeDocsServicer) BatchUpdateDocument(arg1 context.Context, arg2 string, arg3 *docs.BatchUpdateDocumentRequest) (*docs.BatchUpdateDocumentResponse, error) {
	fake.batchUpdateDocumentMutex.Lock()
	ret, specificReturn := fake.batchUpdateDocumentReturnsOnCall[len(fake.batchUpdateDocumentArgsForCall)]
	fake.batchUpdateDocumentArgsForCall = append(fake.batchUpdateDocumentArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 *docs.BatchUpdateDocumentRequest
	}{arg1, arg2, arg3})
	stub := fake.BatchUpdateDocumentStub
	fakeReturns := fake.batchUpdateDocumentReturns
	fake.recordInvocation("BatchUpdateDocument", []interface{}{arg1, arg2, arg3})
	fake.batchUpdateDocumentMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeDocsServicer) BatchUpdateDocumentCallCount() int {
	fake.batchUpdateDocumentMutex.RLock()
	defer fake.batchUpdateDocumentMutex.RUnlock()
	return len(fake.batchUpdateDocumentArgsForCall)
}

func (fake *FakeDocsServicer) BatchUpdateDocumentCalls(stub func(context.Context, string, *docs.BatchUpdateDocumentRequest) (*docs.BatchUpdateDocumentResponse, error)) {
	fake.batchUpdateDocumentMutex.Lock()
	defer fake.batchUpdateDocumentMutex.Unlock()
	fake.BatchUpdateDocumentStub = stub
}

func (fake *FakeDocsServicer) BatchUpdateDocumentArgsForCall(i int) (context.Context, string, *docs.BatchUpdateDocumentRequest) {
	fake.batchUpdateDocumentMutex.RLock()
	defer fake.batchUpdateDocumentMutex.RUnlock()
	argsForCall := fake.batchUpdateDocumentArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3
}

func (fake *FakeDocsServicer) BatchUpdateDocumentReturns(result1 *docs.BatchUpdateDocumentResponse, result2 error) {
	fake.batchUpdateDocumentMutex.Lock()
	defer fake.batchUpdateDocumentMutex.Unlock()
	fake.BatchUpdateDocumentStub = nil
	fake.batchUpdateDocumentReturns = struct {
		result1 *docs.BatchUpdateDocumentResponse
		result2 error
	}{result1, result2}
}

func (fake *FakeDocsServicer) BatchUpdateDocumentReturnsOnCall(i int, result1 *docs.BatchUpdateDocumentResponse, result2 error) {
	fake.batchUpdateDocumentMutex.Lock()
	defer fake.batchUpdateDocumentMutex.Unlock()
	fake.BatchUpdateDocumentStub = nil
	if fake.batchUpdateDocumentReturnsOnCall == nil {
		fake.batchUpdateDocumentReturnsOnCall = make(map[int]struct {
			result1 *docs.BatchUpdateDocumentResponse
			result2 error
		})
	}
	fake.batchUpdateDocumentReturnsOnCall[i] = struct {
		result1 *docs.BatchUpdateDocumentResponse
		result2 error
	}{result1, result2}
}

func (fake *FakeDocsServicer) GetDocument(arg1 context.Context, arg2 string) (*docs.Document, error) {
	fake.getDocumentMutex.Lock()
	ret, specificReturn := fake.getDocumentReturnsOnCall[len(fake.getDocumentArgsForCall)]
	fake.getDocumentArgsForCall = append(fake.getDocumentArgsForCall, struct {
		arg1 context.Context
		arg2 string
	}{arg1, arg2})
	stub := fake.GetDocumentStub
	fakeReturns := fake.getDocumentReturns
	fake.recordInvocation("GetDocument", []interface{}{arg1, arg2})
	fake.getDocumentMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeDocsServicer) GetDocumentCallCount() int {
	fake.getDocumentMutex.RLock()
	defer fake.getDocumentMutex.RUnlock()
	return len(fake.getDocumentArgsForCall)
}

func (fake *FakeDocsServicer) GetDocumentCalls(stub func(context.Context, string) (*docs.Document, error)) {
	fake.getDocumentMutex.Lock()
	defer fake.getDocumentMutex.Unlock()
	fake.GetDocumentStub = stub
}

func (fake *FakeDocsServicer) GetDocumentArgsForCall(i int) (context.Context, string) {
	fake.getDocumentMutex.RLock()
	defer fake.getDocumentMutex.RUnlock()
	argsForCall := fake.getDocumentArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2
}

func (fake *FakeDocsServicer) GetDocumentReturns(result1 *docs.Document, result2 error) {
	fake.getDocumentMutex.Lock()
	defer fake.getDocumentMutex.Unlock()
	fake.GetDocumentStub = nil
	fake.getDocumentReturns = struct {
		result1 *docs.Document
		result2 error
	}{result1, result2}
}

func (fake *FakeDocsServicer) GetDocumentReturnsOnCall(i int, result1 *docs.Document, result2 error) {
	fake.getDocumentMutex.Lock()
	defer fake.getDocumentMutex.Unlock()
	fake.GetDocumentStub = nil
	if fake.getDocumentReturnsOnCall == nil {
		fake.getDocumentReturnsOnCall = make(map[int]struct {
			result1 *docs.Document
			result2 error
		})
	}
	fake.getDocumentReturnsOnCall[i] = struct {
		result1 *docs.Document
		result2 error
	}{result1, result2}
}

func (fake *FakeDocsServicer) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeDocsServicer) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ gcloud.DocsServicer = new(FakeDocsServicer)
