// Code generated by counterfeiter. DO NOT EDIT.
package fakes

import (
	"context"
	"sync"

	"github.com/geofffranks/rookies-bot/gcloud"
	drive "google.golang.org/api/drive/v3"
)

type FakeDriveServicer struct {
	CopyFileStub        func(context.Context, string, string, string) (*drive.File, error)
	copyFileMutex       sync.RWMutex
	copyFileArgsForCall []struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 string
	}
	copyFileReturns struct {
		result1 *drive.File
		result2 error
	}
	copyFileReturnsOnCall map[int]struct {
		result1 *drive.File
		result2 error
	}
	invocations      map[string][][]interface{}
	invocationsMutex sync.RWMutex
}

func (fake *FakeDriveServicer) CopyFile(arg1 context.Context, arg2 string, arg3 string, arg4 string) (*drive.File, error) {
	fake.copyFileMutex.Lock()
	ret, specificReturn := fake.copyFileReturnsOnCall[len(fake.copyFileArgsForCall)]
	fake.copyFileArgsForCall = append(fake.copyFileArgsForCall, struct {
		arg1 context.Context
		arg2 string
		arg3 string
		arg4 string
	}{arg1, arg2, arg3, arg4})
	stub := fake.CopyFileStub
	fakeReturns := fake.copyFileReturns
	fake.recordInvocation("CopyFile", []interface{}{arg1, arg2, arg3, arg4})
	fake.copyFileMutex.Unlock()
	if stub != nil {
		return stub(arg1, arg2, arg3, arg4)
	}
	if specificReturn {
		return ret.result1, ret.result2
	}
	return fakeReturns.result1, fakeReturns.result2
}

func (fake *FakeDriveServicer) CopyFileCallCount() int {
	fake.copyFileMutex.RLock()
	defer fake.copyFileMutex.RUnlock()
	return len(fake.copyFileArgsForCall)
}

func (fake *FakeDriveServicer) CopyFileCalls(stub func(context.Context, string, string, string) (*drive.File, error)) {
	fake.copyFileMutex.Lock()
	defer fake.copyFileMutex.Unlock()
	fake.CopyFileStub = stub
}

func (fake *FakeDriveServicer) CopyFileArgsForCall(i int) (context.Context, string, string, string) {
	fake.copyFileMutex.RLock()
	defer fake.copyFileMutex.RUnlock()
	argsForCall := fake.copyFileArgsForCall[i]
	return argsForCall.arg1, argsForCall.arg2, argsForCall.arg3, argsForCall.arg4
}

func (fake *FakeDriveServicer) CopyFileReturns(result1 *drive.File, result2 error) {
	fake.copyFileMutex.Lock()
	defer fake.copyFileMutex.Unlock()
	fake.CopyFileStub = nil
	fake.copyFileReturns = struct {
		result1 *drive.File
		result2 error
	}{result1, result2}
}

func (fake *FakeDriveServicer) CopyFileReturnsOnCall(i int, result1 *drive.File, result2 error) {
	fake.copyFileMutex.Lock()
	defer fake.copyFileMutex.Unlock()
	fake.CopyFileStub = nil
	if fake.copyFileReturnsOnCall == nil {
		fake.copyFileReturnsOnCall = make(map[int]struct {
			result1 *drive.File
			result2 error
		})
	}
	fake.copyFileReturnsOnCall[i] = struct {
		result1 *drive.File
		result2 error
	}{result1, result2}
}

func (fake *FakeDriveServicer) Invocations() map[string][][]interface{} {
	fake.invocationsMutex.RLock()
	defer fake.invocationsMutex.RUnlock()
	copiedInvocations := map[string][][]interface{}{}
	for key, value := range fake.invocations {
		copiedInvocations[key] = value
	}
	return copiedInvocations
}

func (fake *FakeDriveServicer) recordInvocation(key string, args []interface{}) {
	fake.invocationsMutex.Lock()
	defer fake.invocationsMutex.Unlock()
	if fake.invocations == nil {
		fake.invocations = map[string][][]interface{}{}
	}
	if fake.invocations[key] == nil {
		fake.invocations[key] = [][]interface{}{}
	}
	fake.invocations[key] = append(fake.invocations[key], args)
}

var _ gcloud.DriveServicer = new(FakeDriveServicer)
